### ISSUE TITLE
Probability function for corresponding distribution family not found error 

### ISSUE THREAD

**Issue by DeependraD** [kholsinger/Lecture-Notes-in-Population-Genetics#1]
Here's the first rstan code from Chapter 2 of your book. 

```
data {
  int<lower=0> N; // the sample size
  int<lower=0> k; // the number of A_1 alleles observed
}

parameters {
  real<lower=0, upper=1> p; // the allele frequency
}

model {
  // likelihood
  //
  k ~ binomial(N, p);
  
  // prior
  p ~ dunif(0.0, 1.0);
}
```

I saved it as `binomial-model.stan` as you indicate in the chapter's text and and fitted that with the following R code:

```
require(tidyverse)

library(rstan)
options(mc.cores = parallel::detectCores())

stan_data <- list(N = 20, k = 7)

fit <- stan("binomial-model.stan", data = stan_data, refresh = 0)
```

Console throws following log:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Probability function must end in _lpdf or _lpmf. Found distribution family = dunif with no corresponding probability function dunif_lpdf, dunif_lpmf, or dunif_log
 error in 'model2508183a5e7a_binomial_model' at line 16, column 22
  -------------------------------------------------
    14:   
    15:   // prior
    16:   p ~ dunif(0.0, 1.0);
                             ^
    17: }
  -------------------------------------------------

Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'binomial-model' due to the above error.
In addition: Warning message:
In readLines(file, warn = TRUE) :
  incomplete final line found on 'E:\deependra_files\scripts\binomial-model-stan\binomial-model.stan'
```

Am I not getting something right ? (Pardon me for raising an issue for this supposedly simple job, I am new to stan and went to try it out with your book (out of love, of course)).

**Comment by kholsinger** [comment]
Thank you for pointing out the error. That line should have been

```
p ~ uniform(0.0, 1.0);
```

It's been corrected in the individual notes. It will be corrected in the book version in mid-late December.
[http://darwin.eeb.uconn.edu/eeb348-notes/hardy-weinberg.html](http://darwin.eeb.uconn.edu/eeb348-notes/hardy-weinberg.html)
[darwin.eeb.uconn.edu/eeb348-notes/hardy-weinberg.pdf](darwin.eeb.uconn.edu/eeb348-notes/hardy-weinberg.pdf)

**Comment by kholsinger** [comment]
The LaTeX source for the book version is updated, but I won't update the PDF until mid-late December
